from typing import List, Optional

from pydantic import BaseModel


class EventRead(BaseModel):
    id: int
    path: Optional[str] = None
    description: Optional[str] = None


class EventCreate(BaseModel):
    # user cannot pass id, will be generated by sqlmodel
    path: str
    description: Optional[str] = None


class EventUpdate(BaseModel):
    # only allow to update 1 field
    description: str


class EventListSchema(BaseModel):
    items: List[EventRead]
